version: '3'
services:
  beta:
    container_name: beta
    image: beta
    ports:
      - 8000:80
  alfa:
    container_name: alfa
    image: alfa
    ports:
      - 8001:80
  # nginx:
    #  container_name: nginx
     # image: nginx-php
     # depends_on:
     # - beta
     # - alpha
     # ports:
     #   - 9000:80