version: '3.8'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
  beta:
    container_name: beta
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
          - db
    ports:
      - "5001:80"
    volumes:
      - ./alfa:/var/www/html/
  alfa:
    container_name: alfa
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
          - db
    ports:
      - "5002:80"
    volumes:
      - ./alfa:/var/www/html/
  nginx:
      container_name: nginx
      build: ./nginx
      depends_on:
      - beta
      - alfa
      ports:
        - "8080:80"