version: '3'
services:
  beta:
    container_name: beta
    build:
      context: ./alfa
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./alfa:/var/www/html/
  alfa:
    container_name: alfa
    build:
      context: ./alfa
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    volumes:
      - ./alfa:/var/www/html/
  nginx:
      container_name: nginx
      build: ./nginx
      depends_on:
      - beta
      - alfa
      ports:
        - "8080:80"
  
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example

  adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080